FROM quay.io/pypa/manylinux_2_28_x86_64

LABEL description="A docker image for building portable Python linux binary wheels and Kaldi"
LABEL maintainer="contact@alphacephei.com"

RUN yum -y update && yum -y install \
    libatomic \
    automake \
    autoconf \
    libtool \
    cmake \
    libffi-devel \
    && yum clean all

# OpenBLAS >= 0.3.21 declares LAPACK routines with hidden Fortran string-length arguments in
# lapack.h. The LAPACK used here is CLAPACK (f2c), built below, which has none: drop the
# unconditional LAPACK_FORTRAN_STRLEN_END so Kaldi's calls match the library.
# CLAPACK's CMakeLists targets a CMake older than 3.5, which CMake 4 no longer accepts.
RUN cd /opt \
    && git clone -b vosk --single-branch https://github.com/alphacep/kaldi \
    && cd /opt/kaldi/tools \
    && git clone -b v0.3.34 --single-branch https://github.com/OpenMathLib/OpenBLAS \
    && git clone -b v3.2.1  --single-branch https://github.com/alphacep/clapack \
    && make -C OpenBLAS ONLY_CBLAS=1 DYNAMIC_ARCH=1 TARGET=NEHALEM USE_LOCKING=1 USE_THREAD=0 all \
    && make -C OpenBLAS PREFIX=$(pwd)/OpenBLAS/install install \
    && sed -i '/^#define LAPACK_FORTRAN_STRLEN_END$/d' OpenBLAS/install/include/lapack.h \
    && mkdir -p clapack/BUILD && cd clapack/BUILD && cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. && make -j 10 && find . -name "*.a" | xargs cp -t ../../OpenBLAS/install/lib \
    && cd /opt/kaldi/tools \
    && git clone --single-branch https://github.com/alphacep/openfst openfst \
    && cd openfst \
    && autoreconf -i \
    && CFLAGS="-g -O3" ./configure --prefix=/opt/kaldi/tools/openfst --enable-static --enable-shared --enable-far --enable-ngram-fsts --enable-lookahead-fsts --with-pic --disable-bin \
    && make -j 10 && make install \
    && cd /opt/kaldi/src \
    && ./configure --mathlib=OPENBLAS_CLAPACK --shared --use-cuda=no \
    && sed -i 's:-msse -msse2:-msse -msse2:g' kaldi.mk \
    && sed -i 's: -O1 : -O3 :g' kaldi.mk \
    && make -j $(nproc) online2 rnnlm \
    && find /opt/kaldi -name "*.o" -exec rm {} \;
